MINOR: es-tools: Clean stderr when testing object existence on el9
When checking if an object exists against the Elasticsearch API, force
disable curl --fail-with-body, which is available and enabled by default
on el9. Otherwise we end-up with "curl: (22) The requested URL returned
error: 404" on stderr if the object does not exist.